### ISSUE TITLE
Mystical Agriculture Problem 

### ISSUE THREAD

**Issue by TechnologicApe** [Rikshy/ModularItemFrame#5]
When setting a recipe for essence in a crafting frame it consumes the crystal intended for multiple uses.

**Comment by Rikshy** [comment]
Oh wow, that's crucial. Which version of the mod are you using? I am currently out on game night, but I will look into it after that!

**Comment by TechnologicApe** [comment]
Alpha 1.12.2-2.0 Uploaded on September 22nd.

**Comment by Rikshy** [comment]
thanks for the report. i uploaded a new version, should be available shortly
